### ISSUE TITLE
Where can I find the sample of dirty cow ?

### ISSUE THREAD

**Issue by BiteFoo** [mrmazakblu/Dirty-Cow--app_process32-root-shell-test#1]
Where can I find the sample of dirty cow ? thanks, ^-^

**Comment by TambourineReindeer** [comment]
@BiteFoo I am not sure if I understand your question, but if you mean an example or explanation, here is an article: https://nakedsecurity.sophos.com/2016/10/25/dirtycow-linux-hole-works-on-android-too-root-at-will/

It seems that this exploit was fixed in Google devices and in some Samsung devices as well (clearly not this one): https://nakedsecurity.sophos.com/2016/12/07/news-in-brief-dirtycow-patched-for-android-naked-lack-of-security-south-korea-hacked/

There is also this issue page, which has some useful information: https://github.com/timwr/CVE-2016-5195/issues/14
as well as this: https://github.com/jcadduono/android_external_dirtycow

I hope these help. I hope this helps you too, @mrmazakblu

**Comment by mrmazakblu** [comment]
been waiting for clarification on your question, on finding a "sample". There is both compiled and .c compile code in the git so I don't know what you mean.

**Comment by BiteFoo** [comment]
thanks .

At 2017-01-27 16:46:33, "Reiny Nyt" <notifications@github.com> wrote:


@BiteFoo I am not sure if I understand your question, but if you mean an example or explanation, here is an article: https://nakedsecurity.sophos.com/2016/10/25/dirtycow-linux-hole-works-on-android-too-root-at-will/

It seems that this exploit was fixed in Google devices and in some Samsung devices as well (clearly not this one): https://nakedsecurity.sophos.com/2016/12/07/news-in-brief-dirtycow-patched-for-android-naked-lack-of-security-south-korea-hacked/

There is also this issue page, which has some useful information: timwr/CVE-2016-5195#14
as well as this: https://github.com/jcadduono/android_external_dirtycow

I hope these help. I hope this helps you too, @mrmazakblu
